export const AVAILABLE_SIZES = {
  'xs': 'size-6',
  'sm': 'size-8',
  'md': 'size-12',
  'lg': 'size-16',
  'xl': 'size-20',
  '2xl': 'size-24',
  '3xl': 'size-32',
  '4xl': 'size-40',
  '5xl': 'size-48',
  '6xl': 'size-56',
  '7xl': 'size-64',
  '8xl': 'size-72',
  '9xl': 'size-80',
}

export const FONT_SIZE = {
  'xs': 'text-xs',
  'sm': 'text-sm',
  'md': 'text-base',
  'lg': 'text-lg',
  'xl': 'text-xl',
  '2xl': 'text-2xl',
  '3xl': 'text-3xl',
  '4xl': 'text-4xl',
  '5xl': 'text-5xl',
  '6xl': 'text-6xl',
  '7xl': 'text-7xl',
  '8xl': 'text-8xl',
  '9xl': 'text-9xl',
}